export default [
    { path: "/index", component: "@/pages/index",hideInMenu:false},
    {path: "/",redirect:"/index"},
    { path: "/login", component: "@/pages/login",hideInMenu:true,layout:false},
    { path: "/list", component: "@/pages/list",hideInMenu:false},
    { path: "/recharge", component: "@/pages/recharge",hideInMenu:false},
    { path: "/help", component: "@/pages/help",hideInMenu:false},
    { path: "/my", component: "@/pages/my",hideInMenu:false},
    { path: "/onlinePay", component: "@/pages/index/components/onlinePay",hideInMenu:true,layout:false},
    { path: "/cdkPay", component: "@/pages/index/components/cdkPay",hideInMenu:true,layout:false},
    { path: "/helpInfo", component: "@/pages/index/components/helpInfo",hideInMenu:true,layout:false},
    { path: "/summer", component: "@/pages/index/components/summer",hideInMenu:true,layout:false},
    { path: "/invite", component: "@/pages/index/components/invite",hideInMenu:true,layout:false},
    { path: "/join", component: "@/pages/index/components/join",hideInMenu:true,layout:false},
    { path: "/notice", component: "@/pages/index/components/notice",hideInMenu:true,layout:false},
]